spring:
  application:
    name: springCloud-blog-provider-admin-login
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/blog?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log

server:
  port: 8090

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

comment.avatar: /images/avatar.png

url:
  imageUrl: "file:D:/code/blog/image/"
  visImageUrl: "/pic/**"

